	"// ================================================================\n"
	"// c2htm : c/c++ 設定ファイル\n"
	"// ================================================================\n"
	"\n"
	"\n"
	"// ----------------------------------------------------------------\n"
	"// オプション\n"
	"\n"
	"TAB=4\t\t\t// 入力のタブサイズ. 出力では空白になる\n"
	"LNO=5\t\t\t// 行番号を付ける指定. 値は桁数. 0で無し\n"
	"LNOSEP=\" : \"\t\t// 行番号を付ける場合の、テキストとの間に置く文字列\n"
	"\n"
	"\n"
	"// ----------------------------------------------------------------\n"
	"// C/C++ source 以外の用途に使う場合の調整項目.\n"
	"// ※ C/C++では ` $ @ はだたの文字扱いだが、一応設定しておく\n"
	"\n"
	"// 記号として扱う 記号文字. 最初の=以降行末まで. 空白や// /*は置かないこと\n"
	"SYM\t=!\"#%&'()=~|-^[:]/\\,.{}*+?><;`$@\n"
	"\n"
	"// 名前として扱う 記号文字.\n"
	"NAMESYM\t=_\n"
	"\n"
	"// LINECMTを定義すると、C/C++の // /*コメントをやめ、\n"
	"// 記号1文字から行末までをコメントとする.指定できるのは、記号1文字\n"
	"// LINECMT=#\n"
	"\n"
	"// 1行コメントの、直後の１文字を拡張コメント指定とする\n"
	"//CMTEX1=x\t\t\t\t\t// //x でプログラムのコメントとみなす\n"
	"//CMTEX2=*\t\t\t\t\t// //* を特に強調のコメントとする(もともとはCでのコンパイラ依存コメントへの警告)\n"
	"\n"
	"\n"
	"// ----------------------------------------------------------------\n"
	"// 色やフォントスタイルの設定.\n"
	"//  .C_STR{color:#888833} のようにそのままcssの中身になる\n"
	"\n"
	"C_LNO\t=color:#808080;\t\t\t\t// 行番号の色\n"
	"C_SY\t=color:#661155;\t\t\t\t// 記号\n"
	"C_STR\t=color:#888833;\t\t\t\t// \"文字列\"\n"
	"C_CH\t=color:#888800;\t\t\t\t// 'C'定数.\n"
	"C_ESC\t=color:#805030;\t\t\t\t// 文字列/文字定数中の \\エスケープシーケンス文字\n"
	"C_ESCX\t=color:#FF4411;\t\t\t\t// 通常 source 中の \\ のとき.\n"
	"C_VAL\t=color:#888800;\t\t\t\t// 定数. 100や0x100L など\n"
	"C_OCT\t=color:#802000;\t\t\t\t// 0が１文字のみ以外の8進数.\n"
	"C_CMT\t=color:#90B090;\t\t\t\t// // コメント. C_CMTK定義時は//の直後に空白がある場合の色\n"
	"C_CMTJ\t=color:#20A040;\t\t\t\t// /// /** //! /*! で始まる doxygen(jdoc/qt)コメント\n"
	"C_CMTEX1=color:#A0A0A0\t\t\t\t// ユーザー拡張コメント１の色 ここでは //x\n"
	"C_CMTEX2=color:#F06010\t\t\t\t// ユーザー拡張コメント１の色 ここでは //*\n"
	"//C_CMTK=color:#808080;\t\t\t\t// \"//コメント\".   // の直後に空白がない場合\n"
	"C_SH\t=color:#308080; font-weight:normal;\t// #単語 や #,##\n"
	"C_W1\t=color:#000080; font-weight:normal;\t// 単語グループ1\n"
	"C_W2\t=color:#204080; font-weight:normal;\t// 単語グループ2\n"
	"C_W3\t=color:#206080; font-weight:normal;\t// 単語グループ3\n"
	"C_W4\t=color:#006080; font-weight:normal;\t// 単語グループ4\n"
	"C_W5\t=color:#000080; font-weight:normal;\t// 単語グループ5\n"
	"C_W6\t=color:#204080; font-weight:normal;\t// 単語グループ6\n"
	"C_W7\t=color:#204080; font-weight:normal;\t// 単語グループ7\n"
	"C_W8\t=color:#204080; font-weight:normal;\t// 単語グループ8\n"
	"C_W9\t=color:#204080; font-weight:normal;\t// 単語グループ9\n"
	"C_HT\t=color:#A0A0A0;\t\t\t\t// マーク行以外に使うハーフトーン行設定\n"
	"\n"
	"  //※ 補足\n"
	"  //・SYM= に該当記号文字を登録していない場合、C_指定の動作は不定\n"
	"  //・以下のものは設定がない場合(コメントアウトした場合)、\n"
	"  //  別の指定に置き換わる\n"
	"  //　・C_OCT がない場合、C_VAL で判定\n"
	"  //　・C_ESCXがない場合、C_ESC で判定\n"
	"  //　・C_CMTJがない場合、C_CMT で判定\n"
	"  //　・C_CMTKがない場合、C_CMT で判定\n"
	"  //　その他C_色設定がない場合、ただの文字として判定\n"
	"\n"
	"\n"
	"// ----------------------------------------------------------------\n"
	"// 色をつける単語の登録\n"
	"\n"
	"SHARP\t{\n"
	"\t// #行の単語\n"
	"\t#define\n"
	"\t#if\n"
	"\t#elif\n"
	"\t#else\n"
	"\t#endif\n"
	"\t#ifdef\n"
	"\t#ifndef\n"
	"\t#include\n"
	"\t#pragma\n"
	"\t#error\n"
	"\t#undef\n"
	"\n"
	"\t// プリプロセッサ関係\n"
	"\tdefined\n"
	"\t__FILE__\n"
	"\t__LINE__\n"
	"\t__DATE__\n"
	"\t__FUNCTION__\n"
	"\t__func__\n"
	"\t__VA_ARGS__\n"
	"\n"
	"\t__has_include\n"
	"}\n"
	"\n"
	"WORD1\t{\t// 制御文系\n"
	"\t// c\n"
	"\tbreak\n"
	"\tcase\n"
	"\tcontinue\n"
	"\tdefault\n"
	"\telse\n"
	"\tfor\n"
	"\tgoto\n"
	"\tif\n"
	"\treturn\n"
	"\tswitch\n"
	"\twhile\n"
	"\tdo\n"
	"\n"
	"\t// c++\n"
	"\tdelete\n"
	"\tnew\n"
	"\tthrow\n"
	"\ttry\n"
	"\tcatch\n"
	"\tasm\n"
	"}\n"
	"\n"
	"WORD2\t{\t// 修飾子や型関係\n"
	"\t// c\n"
	"\tauto\n"
	"\ttypedef\n"
	"\tstatic\n"
	"\tstruct\n"
	"\textern\n"
	"\tconst\n"
	"\tvoid\n"
	"\tint\n"
	"\tchar\n"
	"\tlong\n"
	"\tshort\n"
	"\tfloat\n"
	"\tdouble\n"
	"\tsigned\n"
	"\tunsigned\n"
	"\tvolatile\n"
	"\ttypeof\n"
	"\tunion\n"
	"\tenum\n"
	"\tregister\n"
	"\tsizeof\n"
	"\n"
	"\t_Bool\n"
	"\t_Noreaturn\n"
	"\t_Alignas\n"
	"\t_Alignof\n"
	"\t_Complex\n"
	"\t_Static_assert\n"
	"\n"
	"\t// c++\n"
	"\ttypename\n"
	"\tbool\n"
	"\tinline\n"
	"\ttemplate\n"
	"\tusing\n"
	"\tvirtual\n"
	"\tusing\n"
	"\tmutable\n"
	"\tnamespace\n"
	"\texplicit\n"
	"\tfriend\n"
	"\tclass\n"
	"\tprivate\n"
	"\tprotected\n"
	"\tpublic\n"
	"\texplicit\n"
	"\tconst_cast\n"
	"\tstatic_cast\n"
	"\tdynamic_cast\n"
	"\treinterpret_cast\n"
	"\twchar_t\n"
	"\n"
	"\toperator\n"
	"\ttypeid\n"
	"\tthis\n"
	"\tfalse\n"
	"\ttrue\n"
	"\n"
	"\talignas\n"
	"\talignof\n"
	"\tchar16_t\n"
	"\tchar32_t\n"
	"\tconstexpr\n"
	"\tdecltype\n"
	"\tfinal\n"
	"\tnoexcept\n"
	"\tnullptr\n"
	"\toverride\n"
	"\tstatic_assert\n"
	"}\n"
	"\n"
	"WORD3\t{\n"
	"\t// 標準ライブラリ定義の一般的(?)なもの\n"
	"\tNULL\n"
	"\toffsetof\n"
	"\tsize_t\n"
	"\tptrdiff_t\n"
	"\tint8_t\n"
	"\tuint8_t\n"
	"\tint16_t\n"
	"\tuint16_t\n"
	"\tint32_t\n"
	"\tuint32_t\n"
	"\tint64_t\n"
	"\tuint64_t\n"
	"\tintptr_t\n"
	"\tuintptr_t\n"
	"\tintmax_t\n"
	"\tuintmax_t\n"
	"\tstd\n"
	"}\n"
	"\n"
	"WORD4\t{\n"
	"\t// コンパイラ固有\n"
	"\ttypeof\n"
	"\t__cdecl\n"
	"\t__far\n"
	"\t__near\n"
	"\t__huge\n"
	"\t__int64\n"
	"\t__int128\n"
	"\t__inline\n"
	"\t__inline__\n"
	"\t__forceinline\n"
	"\t_inline\n"
	"\t__fastcall\n"
	"\t__stdcall\n"
	"\t__based\n"
	"\tpascal\n"
	"\tcdecl\n"
	"\t__declspec\n"
	"\t__attribute__\n"
	"}\n"
	"\n"
	"\n"
	"\n"
	"// ----------------------------------------------------------------\n"
	"// ヘッダ＆フッター\n"
	"// *fn*  は入力 sorce ファイル名に置き換わる.\n"
	"// *css* は.C_SY{...}のようなスタイル設定に置き換わる\n"
	"\n"
	"\n"
	"HEADER\t{\n"
	"<html>\n"
	"<head>\n"
	"<title> *fn* </title>\n"
	"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=x-sjis\">\n"
	"<style><!--\n"
	".C_PRE{background-color: #f0f0f0;}\n"
	"*css*\n"
	"--></style>\n"
	"</head>\n"
	"<body>\n"
	"<blockquote>\n"
	"<pre class=C_PRE>\n"
	"}\n"
	"\n"
	"\n"
	"FOOTER\t{\n"
	"</pre>\n"
	"</blockquote>\n"
	"</body>\n"
	"</html>\n"
	"}\n"
	"\n"
	"\n"
	"\n"
	"// ----------------------------\n"
	"// 交代ヘッダ＆フッダ 1\n"
	"HEADER1\t{\n"
	"<pre>\n"
	"}\n"
	"FOOTER1\t{\n"
	"</pre>\n"
	"}\n"
	"\n"
	"\n"
	"// 交代ヘッダ＆フッダ 2\n"
	"HEADER2\t{\n"
	"}\n"
	"FOOTER2\t{\n"
	"}\n"
	"\n"
	"\n"
	"// 交代ヘッダ＆フッダ 3\n"
	"HEADER3\t{\n"
	"}\n"
	"FOOTER3\t{\n"
	"}\n"
	"\n"
