    "TAB=4\n"
    "LNO=5\n"
    "LNOSEP=\" : \"\n"
    "SYM =!\"#%&'()=~|-^[:]/\\,.{}*+?><;`$@\n"
    "NAMESYM =_\n"
    "C_LNO   =color:#808080;\n"
    "C_SY    =color:#661155;\n"
    "C_STR   =color:#888833;\n"
    "C_CH    =color:#888800;\n"
    "C_ESC   =color:#805030;\n"
    "C_ESCX  =color:#FF4411;\n"
    "C_VAL   =color:#888800;\n"
    "C_OCT   =color:#802000;\n"
    "C_CMT   =color:#90B090;\n"
    "C_CMTJ  =color:#20A040;\n"
    "C_CMTEX1=color:#A0A0A0;\n"
    "C_CMTEX2=color:#F06010;\n"
    "C_SH    =color:#308080; font-weight:normal;\n"
    "C_W1    =color:#000080; font-weight:normal;\n"
    "C_W2    =color:#204080; font-weight:normal;\n"
    "C_W3    =color:#206080; font-weight:normal;\n"
    "C_W4    =color:#006080; font-weight:normal;\n"
    "C_W5    =color:#000080; font-weight:normal;\n"
    "C_W6    =color:#204080; font-weight:normal;\n"
    "C_W7    =color:#204080; font-weight:normal;\n"
    "C_W8    =color:#204080; font-weight:normal;\n"
    "C_W9    =color:#204080; font-weight:normal;\n"
    "C_HT    =color:#A0A0A0;\n"
    "SHARP   {\n"
    "    #define\n"
    "    #if\n"
    "    #elif\n"
    "    #else\n"
    "    #endif\n"
    "    #ifdef\n"
    "    #ifndef\n"
    "    #include\n"
    "    #pragma\n"
    "    #error\n"
    "    #undef\n"
    "    defined\n"
    "    __FILE__\n"
    "    __LINE__\n"
    "    __DATE__\n"
    "    __FUNCTION__\n"
    "    __func__\n"
    "    __VA_ARGS__\n"
    "    __has_include\n"
    "}\n"
    "\n"
    "WORD1   {\n"
    "    break\n"
    "    case\n"
    "    continue\n"
    "    default\n"
    "    else\n"
    "    for\n"
    "    goto\n"
    "    if\n"
    "    return\n"
    "    switch\n"
    "    while\n"
    "    do\n"
    "    delete\n"
    "    new\n"
    "    throw\n"
    "    try\n"
    "    catch\n"
    "    asm\n"
    "}\n"
    "\n"
    "WORD2   {\n"
    "    auto\n"
    "    typedef\n"
    "    static\n"
    "    struct\n"
    "    extern\n"
    "    const\n"
    "    void\n"
    "    int\n"
    "    char\n"
    "    long\n"
    "    short\n"
    "    float\n"
    "    double\n"
    "    signed\n"
    "    unsigned\n"
    "    volatile\n"
    "    typeof\n"
    "    union\n"
    "    enum\n"
    "    register\n"
    "    sizeof\n"
    "    _Bool\n"
    "    _Noreaturn\n"
    "    _Alignas\n"
    "    _Alignof\n"
    "    _Complex\n"
    "    _Static_assert\n"
    "    typename\n"
    "    bool\n"
    "    inline\n"
    "    template\n"
    "    using\n"
    "    virtual\n"
    "    using\n"
    "    mutable\n"
    "    namespace\n"
    "    explicit\n"
    "    friend\n"
    "    class\n"
    "    private\n"
    "    protected\n"
    "    public\n"
    "    explicit\n"
    "    const_cast\n"
    "    static_cast\n"
    "    dynamic_cast\n"
    "    reinterpret_cast\n"
    "    wchar_t\n"
    "    operator\n"
    "    typeid\n"
    "    this\n"
    "    false\n"
    "    true\n"
    "    alignas\n"
    "    alignof\n"
    "    char16_t\n"
    "    char32_t\n"
    "    constexpr\n"
    "    decltype\n"
    "    final\n"
    "    noexcept\n"
    "    nullptr\n"
    "    override\n"
    "    static_assert\n"
    "}\n"
    "\n"
    "WORD3   {\n"
    "    NULL\n"
    "    offsetof\n"
    "    size_t\n"
    "    ptrdiff_t\n"
    "    int8_t\n"
    "    uint8_t\n"
    "    int16_t\n"
    "    uint16_t\n"
    "    int32_t\n"
    "    uint32_t\n"
    "    int64_t\n"
    "    uint64_t\n"
    "    intptr_t\n"
    "    uintptr_t\n"
    "    intmax_t\n"
    "    uintmax_t\n"
    "    std\n"
    "}\n"
    "\n"
    "WORD4   {\n"
    "    typeof\n"
    "    __cdecl\n"
    "    __far\n"
    "    __near\n"
    "    __huge\n"
    "    __int64\n"
    "    __int128\n"
    "    __inline\n"
    "    __inline__\n"
    "    __forceinline\n"
    "    _inline\n"
    "    __fastcall\n"
    "    __stdcall\n"
    "    __based\n"
    "    pascal\n"
    "    cdecl\n"
    "    __declspec\n"
    "    __attribute__\n"
    "}\n"
    "\n"
    "HEADER  {\n"
    "<html>\n"
    "<head>\n"
    "<title> *fn* </title>\n"
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=x-sjis\">\n"
    "<style><!--\n"
    ".C_PRE{background-color: #f0f0f0;}\n"
    "*css*\n"
    "--></style>\n"
    "</head>\n"
    "<body>\n"
    "<blockquote>\n"
    "<pre class=C_PRE>\n"
    "}\n"
    "\n"
    "FOOTER  {\n"
    "</pre>\n"
    "</blockquote>\n"
    "</body>\n"
    "</html>\n"
    "}\n"
    "\n"
    "HEADER1 {\n"
    "<pre>\n"
    "}\n"
    "FOOTER1 {\n"
    "</pre>\n"
    "}\n"
    "\n"
    "HEADER2 {\n"
    "}\n"
    "FOOTER2 {\n"
    "}\n"
    "\n"
    "HEADER3 {\n"
    "}\n"
    "FOOTER3 {\n"
    "}\n"
