// generated by genfnttex.exe
#ifndef smp_h_included
#define smp_h_included

#include "TexChFontInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

extern TexChFontInfo const		g_chFontTable_smp[];	// [0]=id,n,tw,th,fw,fh [1..]=c,i,x,y,w,h

#ifdef __cplusplus
} //extern "C"
#endif

#endif
