// generated by genfnttex
#ifndef smp_h_included
#define smp_h_included

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ChFontTableInfo {
	unsigned      	chCount;
	unsigned short	texW;
	unsigned short	texH;
	unsigned short	fontW;
	unsigned short	fontH;
	unsigned short	texChW;
	unsigned short	texChH;
	unsigned short	texPage;
} ChFontTableInfo;

typedef struct ChFontTable {
	unsigned      	code;
	unsigned      	index;
	unsigned short	x;
	unsigned short	y;
	unsigned short	w;
	unsigned short	h;
} ChFontTable;

extern ChFontTableInfo const	g_chFontTableInfo;
extern ChFontTable const		g_chFontTable[];

#ifdef __cplusplus
} //extern "C"
#endif

#endif
